apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  labels:
    type: platform
spec:
  project: platform-tools

  sources:
  - repoURL: https://github.com/temitayocharles/helm-charts
    targetRevision: main
    ref: values

  - repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: "0.10.5"
    helm:
      releaseName: external-secrets
      valueFiles:
      - $values/staging-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - Validate=false
